services:
  db: 
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_net
  
  backend:
    build: ./backend
    environment:
      db_name: mydb
      db_password: mypassword
      db_user: myuser
      db_host: db
      db_port: 5432
    ports:
      - "8000:8000"
    networks: 
      - database_net
      - frontend_net
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - frontend_net
    depends_on: 
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend_net
      - database_net
    depends_on:
      - backend
      - frontend
networks:
  frontend_net:
  database_net:
volumes:
  postgres_data:
